moneyadviceservice/dough

- spec/lib/dough/forms/builders/validation_spec.rb
- spec/lib/dough/helpers/form_row_spec.rb
- spec/lib/dough/helpers/renderer_spec.rb
- spec/lib/dough/helpers/tab_selector_spec.rb
- spec/lib/dough/helpers_spec.rb
- spec/lib/dough/html_options_spec.rb
* Flattens namespaces
* Uses `tap` for brevity
Will squash the flattening commits once the PR is approved.
> Tidies up some of the specs

- lib/dough/helpers.rb
- spec/lib/dough/helpers_spec.rb
Add specs to heading_tag helper.
Add documentation to it to see how we can use heading_tag.
This is related to #211.
> Heading tag improvements 

- assets/stylesheets/components/optional/_tab_selector.scss
- assets/stylesheets/lib/_typography.scss
- lib/dough/version.rb
See #214 for background information.
@moneyadviceservice/frontend
> Fixes missing text in TabSelector - Dough issue #214

- assets/js/components/Collapsable.js
- lib/dough/version.rb
- spec/js/fixtures/Collapsable.html
- spec/js/tests/Collapsable_spec.js
Create a concept of collapsable groups which fire an event when a group item is clicked so that the others can close up if required.
This turns the collapsables in the group into an 'accordion'
> Collapsable groups

- assets/js/components/DoughBaseComponent.js
- assets/js/lib/utilities.js
- lib/dough/version.rb
- spec/js/tests/utilities_spec.js
which tests for console object before attempting to use it
> TP-6435: Create generic log method in Dough

- assets/js/lib/utilities.js
- lib/dough/version.rb
- spec/js/tests/utilities_spec.js
Thought it would be useful to have this as a util method, as i've used it a couple of times now in modules.
> id: 6501 comment: Adding debounce method to be used for resize/scroll events

- app/views/dough/helpers/social_sharing_icons/_social_sharing_icons.html.erb
- assets/stylesheets/components/optional/_social_sharing_icons.scss
- assets/stylesheets/lib/_variables.scss
- docs/SocialSharingIcons.md
- docs/helpers/SocialSharingIcons.erb
- lib/dough/version.rb
Dough component for Social Sharing icons to be re-used across main site and tools etc.
> Social sharing

- bower.json
Reverts moneyadviceservice/dough#241
> Revert "Use jQuery 1.11.* to match frontend"

- lib/dough/version.rb
Covers PRs #247, #248 and #250.
> bump 5.9.0 -> 5.10.0

- lib/dough/version.rb
Changes:
* Merge pull request #252 from moneyadviceservice/fix_convert_camel_to_dashed
> [DEV APPROVED] Bump version 5.10.0 -> 5.10.1

- assets/js/components/CollapsableMobile.js
- assets/stylesheets/_lib.scss
- assets/stylesheets/components/common/_collapsable-mobile.scss
- assets/stylesheets/lib/_mediaqueries.scss
This is new component is used when you need the Collapsable menu only in Mobile devices.
> [DEV APPROVED] Move CollapsableMobile from frontend to Dough

- assets/stylesheets/lib/_variables.scss
- lib/dough/version.rb
This is an addition to the previous PR, which updated the colour variable.
This adds the updated version number.
> 7031: Bumps Dough version

- assets/js/components/BackToTop.js
- assets/stylesheets/components/common/_back_to_top.scss
- lib/dough/version.rb
This adds a component to Dough that adds a link for smaller devices to return the user to the top of the page. This is activated when the user scrolls down the content by a certain amount.
> TP: 7225, Comment: Adds BackToTop as a Dough component

- app/views/dough/helpers/social_sharing_icons/_social_sharing_icons.html.erb
- lib/dough/version.rb
This is part 2 of a 2 part ticket, first part is doing the same on the footer in frontend
https://github.com/moneyadviceservice/frontend/pull/1486
> [DEV APPROVED] 7444 - Adding title tags to svgs

- assets/stylesheets/basic.scss
- assets/stylesheets/lib/_variables.scss
- lib/dough/version.rb
Refer to: https://github.com/moneyadviceservice/frontend/pull/1495
> [DEV APPROVED] 7472 - Changing colours for accessibility

- .bowerrc
- app/views/dough/helpers/popup_tip_content/_popup_tip_content.html.erb
- app/views/dough/helpers/popup_tip_trigger/_popup_tip_trigger.html.erb
- docs/PopupTip.md
- docs/helpers/PopupTipContent.erb
- docs/helpers/PopupTipTrigger.erb
- lib/dough/version.rb
This PR is [DEV APPROVED] but amended for build purposes.
> TP: 8647, Comment: Adds Tooltip trigger and content helpers

- Dockerfile
- script/docker_test
- script/test
**Update Ubuntu version**
The Jenkins Docker image utilised Ubuntu 17.04, which has become end of life. This PR rolls back the version to 16.04 LTS (Long Term Support).
**Move to RVM**
Previously we were compiling ruby from source, however we have come across number of errors when older version of Ruby require additional patches to be installed. Therefore I implemented RVM (Ruby Version Manager) to manage the installation and patches.
**Security Testing**
I have also updated the test script to run Brakeman tests for informational purposes. The Jenkins job will not fail if errors and/or warnings occur, but the report will be available in the Jenkins build log.
> [DEV APPROVED] - Update Dockerfile & Jenkins test script for Ubuntu LTS

- Dockerfile
- Jenkinsfile
- script/build
**Adding Post Stage**
Included in the post stage is a step to clean the workspace are the job has completed. This prevents an issue with stale code for further jobs 
**Adding the Build stage**
Introducing the build stage into Jenkins pipeline. It should only run the build stage when on master branch.
> [DEV APPROVED] - Add post stage to clean workspace and gem build stage

- assets/stylesheets/components/common/_popup_tip.scss
- lib/dough/version.rb
Reverts moneyadviceservice/dough#313
Need to apply a further fix.
> Revert "10188 sdc icon misaligned position fix"

- assets/js/components/BackToTop.js
- assets/js/components/DoughBaseComponent.js
- assets/js/components/PopupTip.js
- assets/js/lib/mediaQueries.js
- assets/js/lib/utilities.js
- bower.json
- lib/dough/version.rb
- package.json
- spec/js/fixtures/TabSelector.html
- spec/js/karma.conf.js
- spec/js/tests/CollapsableMobile_spec.js
- spec/js/tests/Collapsable_spec.js
- spec/js/tests/ConfirmableForm_spec.js
- spec/js/tests/DoughBaseComponent_spec.js
- spec/js/tests/PopupTip_spec.js
- spec/js/tests/TabSelector_spec.js
- spec/js/tests/componentLoader_spec.js
- spec/js/tests/mediaQueries_spec.js
- spec/js/tests/utilities_spec.js
[TP9755](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9755&appConfig=eyJhY2lkIjoiQzE1REE4NkE5M0U2Q0VFM0JCM0QyMzM2RUM0MzBGOUQifQ==)
This work upgrades Dough to use JQuery 3.3. 
This involved some small changes to most of the automated tests and then some  more significant work to one component, specifically PopupTip. The tests for this now run and it appears to function properly when mounted on frontend.
> 9755 update j query

- assets/js/components/BackToTop.js
- assets/js/components/ChatPopup.js
- spec/js/fixtures/BackToTop.html
- spec/js/fixtures/ChatPopup.html
- spec/js/test-main.js
- spec/js/tests/BackToTop_spec.js
- spec/js/tests/ChatPopup_spec.js
[TP 10484](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10484/silent)
Introduced logic to raise the chat popup over the "back to top" button that shows in article pages.
> [DEV APPROVED] 10484 floating chat button

- assets/js/components/ChatPopup.js
- spec/js/fixtures/BackToTop.html
- spec/js/tests/ChatPopup_spec.js
[TP 10486](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10486/silent)
This is the final PR for the new WhatsApp Popup [fixture](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=feature/10483).
Automatically hide the popup once the user begins to scroll and provide them with the option to show the button again.
> [DEV APPROVED] 10486 hide chat popup

- assets/js/components/ChatPopup.js
[TP 10486](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10486/silent)
Fixed a bug regarding popup not opening in safari browsers.
> [DEV APPROVED] Fix Safari Bug

- assets/js/components/ChatPopup.js
Fixed some linting errors that prevented the jenkins build.
> 10483 fix tests
