moneyadviceservice/dough

assets/js/lib/componentLoader.js, lib/dough/version.rb, spec/js/fixtures/componentLoader.html, spec/js/tests/componentLoader_spec.js
Use the `[data-dough-defer]` attribute to defer a component:
```html
<div data-dough-component="RangeInput" data-dough-defer>...</div>
```
Then to initialise deferred components, use the optional `includeDeferred` flag as 2nd param in `componentLoader.init($container, true)`
=> Allow deferred components

assets/js/components/Collapsable.js, lib/dough/version.rb, spec/js/fixtures/Collapsable.html, spec/js/tests/Collapsable_spec.js
The current behaviour of Collapsable is to focus the target when opened. Allow this behaviour to be overridden with `config.focusTarget`
=> Add focusTarget config to Collapsable

app/views/dough/forms/builders/validation/_errors_for_field.html.erb, app/views/dough/forms/builders/validation/_summary_for_errors.html.erb, app/views/dough/forms/builders/validation/_summary_for_errors_li.html.erb, assets/js/components/Validation.js, lib/dough/forms/builders/validation.rb, lib/dough/version.rb, spec/js/fixtures/Validation/WithFormID.html, spec/js/tests/Validation_spec.js, spec/lib/dough/forms/builders/validation_spec.rb
This PR makes the form validation functionality, across both ruby and JS, use the form ID when generating the IDs for error labels. If there's no form ID (such as when we're using `fields_for` in a form) it falls back to `object_name`.
So, in the case of Ruby, instead of `#error-1`, we get `#error-form_id-1`.
And, in the case of JS, instead of `#error-field_name` we get `#error-form_id-field_name`.
This helps us avoid duplicate IDs (and links to those IDs) when we have more than one form on the same page.
Background, from slack:
> __Caden Lovelace:__
> I'm working on a form with `fields_for`. Both the form and the `fields_for` use `Dough::Forms::Builders::Validation`. And they both use `form#validation_summary` to display errors
> And each error in the validation summary has an ID link, …
=> Add validation error prefix

assets/js/components/Collapsable.js, lib/dough/version.rb
Allows both `selectors` and `i18nStrings` configs to be set via the `data-dough-collapsable-config` attribute:
```html
<div data-dough-component="Collapsable" data-dough-collapsable-config='{"selectors": {"activeClass": "is-active"},{"i18nStrings": {"open": "Show categories","close": "Hide categories"}}'>...</div>
```
Also bumps Dough to _5.5.0_
=> Move selectors and i18nStrings into config

assets/js/components/Collapsable.js, assets/js/components/DoughBaseComponent.js, assets/js/components/FieldHelpText.js, assets/js/components/RangeInput.js, assets/js/components/TabSelector.js, assets/js/components/TabularTooltip.js, assets/js/components/Validation.js, assets/js/lib/componentLoader.js, assets/js/lib/utilities.js, lib/dough/version.rb, spec/js/fixtures/DoughBaseComponent.html, spec/js/fixtures/DoughBaseComponentExtended.html, spec/js/test-main.js, spec/js/tests/DoughBaseComponent_spec.js, spec/js/tests/componentLoader_spec.js, spec/js/tests/utilities_spec.js
This PR accomplishes the following:
* Enables a component to be instantiated using its constructor and stamped (`new FooComponent()`) without using `componentLoader`. Before initialising a component directly would return stamp `data-dough-undefined-initialised="yes"`. It now properly sets `data-dough-foo-initialised="yes"`. It does this by moving responsibility of setting the `componentName` to `DoughBaseComponent`. See https://github.com/moneyadviceservice/dough/issues/218 for the original bug. 
* Adds `componentName`'s to default Dough components
* Adds specs for DoughBaseComponent
=> Fix missing componentName in DoughBaseComponent

assets/stylesheets/components/optional/_tab_selector.scss
- due to a change (https://github.com/moneyadviceservice/dough/commit/8f484b050078d0f52503b4085cc2b8b6ae2df1f1) by Justin back in Feb, the internal name
of the tab selector component has changed from 'tabselector'
to 'tab-selector'
- fixes the css which relies on this name
=> TP-6422: Fix bug with visibility of tab selector component

assets/js/lib/mediaQueries.js, bower.json, lib/dough/version.rb, spec/js/test-main.js, spec/js/tests/mediaQueries_spec.js
- Added check for mediaQuery support when calling
getSize to ensure JS doesn't break on IE8
- added Squire to bower deps to allow for
AMD module mocking so we can test behaviour
with/without mediaQuery support
=> TP-6297: Fix IE8 issue with tab selector dough component

assets/stylesheets/components/common/_button.scss, assets/stylesheets/components/common/_form.scss, assets/stylesheets/components/common/_pagination.scss, assets/stylesheets/components/common/_validation_summary.scss, assets/stylesheets/components/optional/_form_input_range.scss, assets/stylesheets/components/optional/_tab_selector.scss, lib/dough/version.rb
- the comments in the Sass files for these components
drive the documentation created by KSS
- the dough comments appear to override comments
which are added to the dough theme on the MAS website
- by removing these comments we allow the dough theme
in the frontend MAS website to control what is output
in the styleguide and not dough
=> id:6501 comment: Removing a bunch of comments in Sass

assets/js/components/ConfirmableForm.js, lib/dough/version.rb, spec/js/fixtures/ConfirmableForm.html, spec/js/fixtures/ConfirmableFormOnInput.html, spec/js/test-main.js, spec/js/tests/ConfirmableForm_spec.js
This adds the ConfirmableForm component originally created within the RAD codebase (https://github.com/moneyadviceservice/rad/commit/d2d4f3b6739e51346b6ac50fdb082229c68c0624?diff=unified).
We've had to port the functionality across to https://github.com/moneyadviceservice/webfeeds to add a piece of functionality. This PR would allow us to remove the duplication from both both RAD and Webfeeds.
=> Add ConfirmableForm component

assets/js/components/ConfirmableForm.js
I had ran the `jshint` command line tool, but missed there was an additional `jscs` command line tool for linting. Travis builds didn't raise an error, but the GO server failed to build the gem because of two errors:
```
One space required after "if" keyword at assets/js/components/ConfirmableForm.js :
65 |
66 |    $form.submit(function(e) {
67 |      if(window.confirm(self.message)) {
----------------^
68 |        return true;
69 |      } else {
One space required after "if" keyword at assets/js/components/ConfirmableForm.js :
82 |   */
83 |  ConfirmableFormProto.getFormFromComponent = function() {
84 |    if(this.$el.is('form')) { return this.$el; }
--------------^
85 |    return this.$el.parents('form').first();
86 |  };
```
=> add single whitespaces after if keyword

bower.json
Build is failing to due to version mismatches on jQuery, probably safer to specify the same version string as frontend and the engines use here.
=> Use jQuery 1.11.* to match frontend

assets/js/components/Validation.js, spec/js/tests/Validation_spec.js
Some forms have only one field and so showing both the validation summary and the inline error when client-side validation fails is overkill and can look like duplication to the end user. This PR adds a config option to the client-side validation that allows you to toggle on or off the validation summary.
=> Validation update - validation summary

package.json
This change adds 
```diff
+    "mocha": "^2.3.4",
+    "requirejs": "^2.1.22",
```
as local development dependencies.
(Also npm install automatically alpha sorted the list)
In a fresh install, `npm install` outputs:
```sh
$ npm install
npm WARN karma-mocha@0.1.10 requires a peer of mocha@* but none was installed.
npm WARN karma-requirejs@0.2.3 requires a peer of requirejs@~2.1 but none was installed.
```
And sure enough the tests fail without these packages.
Does anyone know any good reason why this was necessary and why we shouldn't do this?
It may be that in the past somewhere in the dependency tree these packages were automatically being included (e.g. via karma-mocha and karma-requirejs) but they aren't now.
=> Add deps on mocha and requirejs (and alpha sort deps list)

assets/js/components/Validation.js, spec/js/tests/Validation_spec.js
Some forms have only one field and so showing both the validation summary and the inline error when client-side validation fails is overkill and can look like duplication to the end user. This PR adds a config option to the client-side validation that allows you to toggle on or off the inline validation.
=> Validation update - inline validation

assets/js/components/Validation.js, spec/js/fixtures/Validation/Checkboxes.html, spec/js/fixtures/Validation/RadioButtons.html, spec/js/tests/Validation_spec.js
This PR brings client-side validation to checkboxes as well as radio buttons and text fields. As long as all of the checkboxes in the group have the same name and are within the same `form__row`, you can validate that at least one checkbox has been checked.
In order to prevent surprising UI behaviour I also disabled blur events for checkboxes because, unlike radio buttons, you can check and then uncheck a checkbox. This was leading to situations where, if you checked a checkbox and then unchecked it again, when you went to check on the next checkbox in the group it would display an error.
=> Validate checkboxes

assets/js/components/Print.js, lib/dough/version.rb, spec/js/fixtures/Print.html, spec/js/test-main.js, spec/js/tests/Print_spec.js
Adds a very very simple Dough component that lets you easily create a "Print" button on the page, which when pressed opens the browser's print dialog.
Get it loaded into your project in the usual MAS way using RequireJS, then tag your button like so:
```html
<button data-dough-component="Print">
Print
</button>
```
=> [DEV APPROVED] Add a Print component

assets/js/components/RangeInput.js, spec/js/fixtures/RangeInput.html, spec/js/tests/RangeInput_spec.js
The RangeInput (slider) component in Dough takes an input field, checks for browser support of `input type="range"` and if supported, creates a range input by cloning the original input and changing the type of the clone to 'range'.
This PR changes two things in the RangeInput component in Dough. 
1. Adds an optional config parameter for any HTML Attributes that should be ignored when cloning the original input.
2. When the range input is updated, triggers a 'change' event on the text input - this may be needed if a JS data-binding framework is used which is watching for changes to the field.
=> [DEV APPROVED] Adding new config parameter for RangeInput

assets/stylesheets/components/optional/_tab_selector.scss, lib/dough/version.rb
Provides a way to use the MAS tab styles to link to separate pages.
Currently the tab_selector styles are designed to add tabs to switch between content blocks within a single page. But for RAD we wanted to reuse the house style to switch between separate pages.
To make this possible we need a way to override the default behaviour that hides the tabs until the related JavaScript component has initialised. Because for our case we don't need the JS component.
E.g. if you just define a set of tabs without the JS component:
```html
<div class="tab-selector">
<div class="tab-selector__triggers-outer">
<div class="tab-selector__triggers-inner">
<div class="tab-selector__trigger-container">
<a class="tab-selector__trigger is-active" href="firm_details.html">Firm details</a>
</div>
<div …
```
=> [DEV APPROVED] Make it possible to use the tab_selector style without JavaScript

assets/js/lib/mediaQueries.js
* getSize() function was returning ""mq-s"" instead of "mq-s". I'm stripping the extra double quotes away to allow it's internal atSmallViewport() to work correctly.
* init() function wasn't appending the testElement to the BODY tag correctly because it was writing it's value to a parameter variable.
* Added an updatePageClass() function which writes the current mq- mediaquery value to the HTML tag so we can use these as prefixes in our SCSS to better support mediaQuery aware components.
=> [DEV APPROVED] Dough mediaQueries bug fixes x2 + 1x feature

.gitignore, assets/stylesheets/_templates/karma_tests.scss, package.json, spec/js/fixtures/CollapsableMobile.html, spec/js/fixtures/stylesheets/lib.css, spec/js/karma.conf.js, spec/js/test-main.js, spec/js/tests/CollapsableMobile_spec.js, test.sh
Adds tests for the CollapsableMobile.js component that are mobile-specific (or more accurately, small-screen-specific). The way that this PR does is by running the full suite of Karma tests in an alternative browser size.
One of the extra requirements for this was creating a CSS file with our media queries (which gets recompiled as part of the test script), because mediaqueries within Dough JS depend on CSS.
=> [DEV APPROVED]Karma tests for collapsable mobile using two PhantomJS browsers

assets/js/components/CollapsableMobile.js
Whilst writing the karma tests I found a bit of superfluous functionality in the CollapsableMobile component that we recently added. The component does not need an event handler on window.resize. The component CSS will handle the change in layout when the window is resized to match a new media query.
=> [DEV APPROVED] Refactoring Collapsable Mobile, resize event superfluous

lib/dough/version.rb
Update to 5.13 as this is a minor functional release.
=> Increasing Dough version no

assets/js/components/Collapsable.js, assets/stylesheets/components/common/_collapsable.scss, lib/dough/version.rb, spec/js/fixtures/Collapsable.html, spec/js/tests/Collapsable_spec.js
For the Budget Planner redesign the Collapsable Dough component is used extensively. This PR adds two config options to the component:
1. The option to specify whether the dropdown icon appears on the left or the right
2. The option to show the 'show / hide' label (previously this was accessibly hidden)
With both enabled:
=> [DEV APPROVED Adding the showlabels and iconPosition atts for Collapsable

lib/dough/version.rb, spec/js/tests/CollapsableMobile_spec.js, spec/js/tests/Collapsable_spec.js
In a previous PR I accidentally committed an 'only' command to the Karma tests in Dough (d'oh!). This PR removes this and fixes a test.
=> Removing 'only' command and fixing test

assets/js/components/Collapsable.js, assets/stylesheets/components/common/_collapsable.scss, lib/dough/version.rb, spec/js/tests/Collapsable_spec.js
This PR causes the content of a 'collapsable' module to be visible on the page before JavaScript is being loaded. When the Dough component is initialised, anything that should be hidden gets hidden.
The previous behaviour was that if JS was enabled, any 'collapsable' content would be hidden by the CSS, and only shown once JS was initialised. This meant a longer wait for users to see content, as well as the risk that any JS errors / failure to load would result in hidden content.
=> Dough Collapsable modules show content whilst page renders

assets/js/components/SearchFocus.js, lib/dough/version.rb, spec/js/fixtures/SearchFocus.html, spec/js/test-main.js, spec/js/tests/SearchFocus_spec.js
This addresses an accessibility issue whereby the focus after a search returns to the top of the page rather than to the first result or, where there are no results, to the input field. 
It is used by PR 1518 in frontend (https://github.com/moneyadviceservice/frontend/pull/1518)
=> [DEV APPROVED] TP: 7569, Comment: Updates element that has focus after search

app/views/dough/helpers/social_sharing_icons/_social_sharing_icons.html.erb, lib/dough/version.rb
This PR removes SVG's from the tab order, this relates to the social share icons on the article pages, ``tabindex="-1"`` was mentioned in the ticket for this task but had no effect in IE11, ``focusable="false"`` worked in all cases.
**Related PR's**
Publify
https://github.com/moneyadviceservice/publify/pull/214
Frontend
https://github.com/moneyadviceservice/frontend/pull/1566
=> [DEV APPROVED] 7673 - Adding focusable false to social share SVGs

assets/stylesheets/components/common/_collapsable-mobile.scss, lib/dough/version.rb
The CSS for the 'collapsable' Dough component was slightly more specific than the 'collapsable-mobile' component. This meant that it was overriding it and causing a [bug](https://moneyadviceservice.tpondemand.com/entity/7707) where the 'collapsable-target' container was always hidden on desktop.
This PR makes the CSS for 'collapsable-mobile' slightly more specific. It needs to be able to override the 'collapsable' module, not the other way around.
=> [DEV APPROVED]Increasing CSS specificity in collapsable mobile

assets/stylesheets/components/common/_validation_summary.scss, assets/stylesheets/components/optional/_tab_selector.scss, lib/dough/version.rb
This PR just fixes an SCSS `@extend` that doesn't exist, currently this just gives a warning, but it prevents us from upgrading our SASS-Rails gem.
=> [DEV APPROVED]Removing SCSS errors - @extends that don't exist

app/views/dough/helpers/social_sharing_icons/_social_sharing_icons.html.erb, lib/dough/version.rb
Adding ``data-dough-shared-on`` attributes to each of the social links, these will be used in the frontend branch:
https://github.com/moneyadviceservice/frontend/compare/feature/feedback-like-dislike-articles
We will use these to record which of the social media links have been used to share an article
=> [DEV APPROVED] 7708 - Adding data attributes to social links

assets/js/components/Validation.js, assets/stylesheets/components/common/_validation_summary.scss, lib/dough/version.rb
In the RAD ticket (https://github.com/moneyadviceservice/rad_consumer/pull/309) we are using the dough validation component, however we do not need the link on the validation text as shown below:
This PR adds a modified version which will not add a link and anchor to the validation error message:
(Below screenshot shown with additional style added in rad_consumer)
=> [DEV APPROVED]7756 - Adding modified validation - no link

app/views/dough/helpers/social_sharing_icons/_social_sharing_icons.html.erb, lib/dough/version.rb
This PR adds the generic `.svg-icon` class that we use in Frontend for styling SVG Icons.
=> [DEV APPROVED] 7847 - Adding SVG Icon classes

assets/stylesheets/lib/_variables.scss, lib/dough/version.rb
This PR is part of the task to update the yellow-light colour across the site to #fed40b, this exists in Yeast but also here, we should refactor this once this task is done.
=> [DEV APPROVED] 8150 - Updating Yellow

dough-ruby.gemspec, lib/dough/version.rb
Dough is failing on the test because of a known error in the later version of rails:
https://github.com/rails/rails/issues/28529
This PR reverts the version back to a pre v5 Version and fixes the error
=> [DEV APPROVED] Reverting rails version to pre 5 to avoid cache bug

assets/js/components/PopupTip.js, assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb, spec/js/fixtures/PopupTip.html, spec/js/test-main.js, spec/js/tests/PopupTip_spec.js
This PR adds a new component for a popup tooltip.
| Screenshot |
|------------|
```
<div data-dough-component="PopupTip">
<button data-dough-popup-trigger type="button" class="popup-tip__button">
</button>
<div data-dough-popup-content class="popup-tip__content">
<h3 class="popup-tip__title">Title</h3>
<p>Content</p>
<button data-dough-popup-close type="button" class="popup-tip__close">
<span aria-hidden="true">
</span>
<span class="visually-hidden">
</span>
</button>
</div>
</div>
```
**Using WPCC as an example**
=> 8380 - Adding popup tooltip

assets/js/components/PopupTip.js
Fixes the below error on the build server:
```
09:57:18.493 Illegal space after key at assets/js/components/PopupTip.js :
09:57:18.493     37 |
09:57:18.493     38 |    this.$popup.css({
09:57:18.493     39 |      'top' : triggerPos.top
09:57:18.494 -------------------^
09:57:18.494     40 |    });
09:57:18.494     41 |
09:57:18.494 
09:57:18.495 
09:57:18.495 1 code style error found.
09:57:18.516 [go] Current job status: failed.
```
=> Fixes spacing error

assets/js/components/PopupTip.js, lib/dough/version.rb
Currently the component calculates the position from the top of the page to the trigger, this isnt a good approach, this PR removes this calculation.  It will be less intensive to use CSS positioning instead.
=> 8380 - Adjust how tooltip is positioned

assets/js/components/PopupTip.js, assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb, spec/js/fixtures/PopupTip.html, spec/js/tests/PopupTip_spec.js
This PR makes an improvement to the behaviour of the popuptip component when a user clicks on the show help icon:
1) User clicks button:
2) Focus shifts to popuptip content, screen reader will read the contents automatically (Outline is hidden using CSS attribute ``outline: none``)
3) On the next tab click, the close button is selected:
4) Focus is then returned to the help icon, placing the user back to their original point:
Please note that this requires a change to the markup of our tools which currently use this component.
New Markup:
```
<button type="button" class="popup-tip__button" data-dough-popup-trigger>
<span aria-hidden="true">i</span>
<span class="visually-hidden">show</span>
</button>
<div data-dough-popup-container class="popup-tip__container">
<p data-dough-popup-content …
```
=> [DEV APPROVED] Improves screen reader accessibility- PopupTip.js

assets/js/components/TabSelector.js, lib/dough/version.rb, spec/js/tests/TabSelector_spec.js
This PR addresses two accessibility/usability issues:
**Link role**
[TP Link - 7960](https://moneyadviceservice.tpondemand.com/entity/7960)
The tabs shown here are being picked up as buttons by Dragon. This could be confusing for a voice activation user as most tabs are picked up as links by Dragon. **Solution**: use the role of ‘link’ for these elements.
**aria-hidden=true in active tab**
[TP Link 7970](https://moneyadviceservice.tpondemand.com/entity/7970)
This was a bug in the TabSelector component: `aria-hidden` was set to `true` on all tabs when the page loaded, including the active tab. Instead, `aria-hidden` should only be `true` for the inactive tabs.
=> [DEV APPROVED] 7960, 7970 - Accessibility role link, and aria-hidden in tabs

.bowerrc, app/views/dough/helpers/popup_tip_content/_popup_tip_content.html.erb, app/views/dough/helpers/popup_tip_trigger/_popup_tip_trigger.html.erb, docs/PopupTip.md, docs/helpers/PopupTipContent.erb, docs/helpers/PopupTipTrigger.erb, lib/dough/version.rb, package.json
[TP8647](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8479&appConfig=eyJhY2lkIjoiREREN0YzQTYyNjg0NEFCOEQxQkVFM0YwNkVDMjhFRkEifQ==&searchPopup=userstory/8647)
This PR creates two new Dough Helpers that can be used across the site to replace the various tooltips that are used throughout our tools. These are based on the partials created in WPCC and have no styles associated with them.
* provides the icon that shows the tip
* allows us to pass in two optional values:
* the visually-hidden text for screen-readers (e.g. “show help”)
* a class name which is necessary in some instances on WPCC
* provides the container for the content that is displayed in the tip
* allows us to pass in four optional values: 
* a title which is used in some instances on WPCC
* the …
=> 8647 tooltip icon

build.sh, lib/dough/version.rb
[TP8729](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8729)
The main work for this has already been merged but there are build problems that appear to be connected to a known issue with GitHub pages. This means that there will be no documentation for the tooltip helpers on Made with Dough but the helpers should be useable.
=> [DEV APPROVED] TP: 8729, Comment: Disable GitHub pages

app/views/dough/helpers/popup_tip_content/_popup_tip_content.html.erb, lib/dough/version.rb
The popup tip content boxes may include a title element, but most of them do not in practice. 
Where a popup content does not have a title and where JS is disabled - the automatically displayed text starts with a colon, which it shouldn't.
This is a ticket to remove the colon in those circumstances.
| Current (Non JS) |
|---------|
|<img width="795" alt="screen shot 2017-12-19 at 10 18 04" src="https://user-images.githubusercontent.com/13165846/34152285-fd75524e-e4a5-11e7-942c-bd39611d0a68.png">|
| Updated with title | Updated no title |
|-------------------|-----------------|
|<img width="730" alt="screen shot 2017-12-19 at 10 20 59" src="https://user-images.githubusercontent.com/13165846/34152395-594b4d30-e4a6-11e7-9049-d304438d31da.png">|<img width="730" alt="screen shot 2017-12-19 at …
=> [DEV APPROVED] 8744 - Tooltip component bug

spec/js/tests/ConfirmableForm_spec.js, spec/js/tests/TabSelector_spec.js, spec/js/tests/utilities_spec.js
[TP8781](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8781)
There are some Karma tests in Dough that are using soon-to-be-deprecated methods. The following warnings thrown by running the tests: 
- sandbox.stub(obj, 'meth', val) is deprecated and will be removed from the public API in a future version of sinon. Use sandbox.stub(obj, 'meth').callsFake(fn) instead in order to stub a function.
- sinon.stub(obj, 'meth', fn) is deprecated and will be removed from the public API in a future version of sinon. Use stub(obj, 'meth').callsFake(fn)
This PR updates these so that they will not break. 
The tests affected are: 
- ConfirmableForm_spec.js
- …
=> [DEV APPROVED] 8781 karma update deprecated methods

assets/js/components/BackToTop.js, lib/dough/version.rb, package.json, spec/js/fixtures/BackToTop.html, spec/js/karma.conf.js, spec/js/test-main.js, spec/js/tests/BackToTop_spec.js, spec/js/tests/ConfirmableForm_spec.js, spec/js/tests/TabSelector_spec.js, spec/js/tests/utilities_spec.js
[TP7313](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/8733&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/7317)
TECH DEBT: 
When implementing [TP7225](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=userstory/7317&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/7225) we did not complete the Unit Tests for that work, which was to add a link on article pages in the mobile view to allow users to scroll back to the top of the page.
This ticket adds these tests that check that:
- the link element has been added to the DOM
- the footer has the required extra space to display this
- the link is displayed when the user has scrolled to the predetermined point
- …
=> [DEV APPROVED] 7317 back to top unit tests

.travis.yml, dough-ruby.gemspec, lib/dough/forms/builders/validation.rb, lib/dough/version.rb, spec/lib/dough/forms/builders/validation_spec.rb
**No TP cards** but it is blocking the fincap since this [PR](https://github.com/moneyadviceservice/fin_cap/pull/39)
This gem was added to Fincap [here](https://github.com/moneyadviceservice/fin_cap/pull/39/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R8) but it was raising the errors that Dough was not compatible with Rails 5.
So this PR addresses the Rails 5 update and fix for it which is explained on the commit message.
=> Update rails for fincap

assets/js/lib/mediaQueries.js, lib/dough/version.rb
This PR adds in medium and large breakpoint functions to mediaQueries.
This is being done as part of [TP9480](https://moneyadviceservice.tpondemand.com/entity/9480-js-to-resize-fee-blocks-when) as the JS breakpoint support needs to be higher
=> [DEV APPROVED] Adding medium and large breakpoints in mediaQueries

.gitignore, assets/js/components/DoughBaseComponent.js, assets/js/constants/DoughEventConstants.js, spec/js/test-main.js, spec/js/tests/DoughBaseComponent_spec.js
https://moneyadviceservice.tpondemand.com/entity/9847-modify-doughbasecomponent
This is one piece of work being done to update the Dough gem.
Adding an index attribute for each DoughBase Component makes it a lot harder for these instances to be referenced and called. 
The other part of the work in this ticket was to publish events on the success/failure of component initalization. 
We've started off with having event strings being stored in once central location as constants. We had a long discussion over the best way of implementing these, firstly for performance (with minification), secondly as to the best place for each of these events to be stored - along with the best convention to use for these. 
Please feel free to comment on this approach and if you feel like there may be a nicer …
=> 9847 modify dough component

assets/js/components/PopupTip.js, assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb, package.json, spec/js/fixtures/PopupTip.html, spec/js/karma.conf.js, spec/js/tests/PopupTip_spec.js
[TP9392](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=userstory/9392/silent)
The Dough tooltip component currently always displays in the same position, meaning that in some circumstances it appears relatively distant from the icon that triggers it. This is particularly noticeable on the Debt Advice Locator tool and creates a confusing user experience (as below). 
The work in this PR sets the position of the popup to be related to the trigger position (see below). This is aligned with a lateral variation depending on the trigger position relative to the centre of the page so that the popup will not display off-screen.
=> [DEV APPROVED] 9392 popup tip position

assets/js/lib/utilities.js
The ViewPortManager component (TP-9800) uses both a debounce and throttle function. These were local to the component during development. We have noticed there is a debounce function already in the DoughCore utilities module so it makes sense to move the throttle function to that module and then use both the throttle and debounce functions from that module.
=> 9912 throttle fn for view portmanager in tp9800

assets/js/lib/componentLoader.js, spec/js/tests/componentLoader_spec.js
Here we modify the componentLoader so it dispatches an Completion event for our code to hook into. We already have domReady and window.load events. This Component_Complete Dough Event will allow us to know when all the dough components are ready.
As part of this PR, we are also outputting any errors fired from the .init() fucntion that are trapped by the try...catch.
=> [DEV APPROVED] 9852 component loader

assets/js/components/PopupTip.js, assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb
[TP10188](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/10188)
The recently updated i icons are displaying badly on the Stamp Duty Calculator tool. It is positioned wrongly and the width of the overlay is essentially zero. 
This is caused by the component dynamically setting its position and size relative to the icon itself. 
The solution in this PR is to set these values relative to the parent of the icon that is a more reliable reference.
=> [DEV APPROVED] 10188 sdc icon misaligned

assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb
[TP10188](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/10188)
As a result of testing a problem was found on the Debt Advice Locator tool. This PR is to restore a style removed in PR312 to fix this and redeploy for further testing.
=> 10188 sdc icon misaligned position fix

lib/dough/version.rb
Bumping major version of dough. This is due to the previous PR introducing breaking changes to tools when bumped and extra steps need to be taken to upgrade to this version
=> Bump major version due to breaking change

jenkins/Dockerfile, jenkins/build, jenkins/test
In an effort to increase efficiency and speed, we can now use a pre-bundled Docker image which includes all gems & dependancies.
Changes include;
- Use Pre-bundled base image in Jenkins
- Updates to test script
=> Use bundled base image for Jenkins

assets/js/components/PopupTip.js, lib/dough/version.rb
[TP9755](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/9755/silent)
During the JQuery upgrade work on Dough an earlier piece of work, dealing with the positions of the Popup Tips was broken. This work restores the change that was removed. 
Currently on Preview: 
Updated
=> [DEV APPROVED] 9755 popup tip position fix

dough-ruby.gemspec, lib/dough/version.rb
Needed in order to bump Fincap Rails version: [TP-19385](https://moneyadviceservice.tpondemand.com/entity/10385-upgrade-fincap-rails-from-506-to)
We need to bump patch versions in apps (Eg: Fincap) using Rails 5.0.x
due to critical security updates.
The dependency restriction on Dough Ruby blocks upgrades of apps using
it to 5.0.7.
As everything under 5.0.x is a PATCH update meant to solve bugs or fix
security issues, with no feature changes, relaxing the Rails dependency
restriction to "Anything under Rails 5.1" will allow any further Patch
update in the host apps to be applied without having to come again to
update this restriction.
I assume that if we need to update any app using Dough to Rails 5.1/5.2
we will want to do specific testing to get sure they're compatible.
=> TP-10385: Relax rails version restriction

assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb
[TP 10495](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10495/silent)
Changes needed for styling of span elements inside popups.
These changes were made due to a ticket in the debt-advice-locator tool for a text change [PR159](https://github.com/moneyadviceservice/debt-advice-locator/pull/159).
=> [DEV APPROVED] Added styles for popup span

assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb
[TP 10508](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10508/silent) and refer to [TP 9256](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=bug/9256)
In some instances, the page content overlaps the popup-tip content. The first time this bug was noticed, it was fixed by adding a style to wpcc, [refer to pr#211 on wpcc](https://github.com/moneyadviceservice/wpcc/pull/211). Ideally the fix should have been applied to dough as the popup component is used across the site and should be designed to be dropped into any engine/tool without the need for customisation. 
This pr adds the requisite style to the dough component to ensure the popup …
=> TP 10508 Pop up tip overlap

assets/js/components/ChatPopup.js, spec/js/fixtures/BackToTop.html, spec/js/tests/ChatPopup_spec.js
[TP 10485](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10485/silent)
This PR implements the opening and closing functionality to the webchat popup as well as the service select and buttons for WhatsApp and Webchat.
[PR 2122](https://github.com/moneyadviceservice/frontend/pull/2122) on frontend sets the elements, styles and translations for the popup.
=> [DEV APPROVED] 10485 popup channel select

assets/js/components/BackToTop.js, assets/js/components/ChatPopup.js, assets/stylesheets/components/common/_popup_tip.scss, lib/dough/version.rb, spec/js/fixtures/BackToTop.html, spec/js/test-main.js, spec/js/tests/BackToTop_spec.js, spec/js/tests/ChatPopup_spec.js
Part of [TP 10483](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&searchPopup=feature/10483)
This PR merges tickets 10484, 10485 and 10486 into master.
Floating webchat icon in the bottom right of the page and when I tap it then I should see a dropdown of categories with a 'Start web chat' button always visible and when I select either Pensions & Retirement or Debt & Borrowing then I should also see the 'Start Whatsapp' button and when I tap either of these buttons then that should initiate the appropriate chat as per the page footers.
And when I begin to scroll then the icon should slide out, leaving behind a small tab which reveals the popup on click.
=> [DEV APPROVED] 10483 whatsapp webchat mobile interaction

assets/js/components/BackToTop.js, assets/js/components/CovidBanner.js, lib/dough/version.rb, spec/js/fixtures/CovidBanner.html, spec/js/test-main.js, spec/js/tests/CovidBanner_spec.js
[TP11363](https://maps.tpondemand.com/entity/11363-sticky-banner-on-mas-website-for)
This work adds a banner to direct users to our articles on Coronavirus. 
There are three PRs that make up the implementation of this component: 
- [PR2201](https://github.com/moneyadviceservice/frontend/pull/2201) in frontend that provides the content and markup for the banner, as well as the Rails functionality to render the component only when this is not recorded in a Cookie as having been previously dismissed, and the reference to the associated Dough component. 
- [PR61](https://github.com/moneyadviceservice/yeast/pull/61) in yeast that provides the styles for the component, and which will be shared with other repos, such as RAD. 
- PR338 in dough (this PR) that provides the JavaScript component and …
=> 11363 sticky banner coronavirus info

assets/images/exclamation_mark.svg, assets/js/components/ThirdPartyCookieAccess.js, jenkins/test, lib/dough/version.rb, package.json, spec/js/test-main.js, spec/js/tests/CovidBanner_spec.js, spec/js/tests/ThirdPartyCookieAccess_spec.js
This is one of 2 PRs to implement [TP-11920](https://maps.tpondemand.com/entity/11920-credit-card-calculator-implement-third-party), the task to dal with the issue concerning third party cookies on syndicated tools. Because these are embedded onto partner sites via an iFrame some browsers - currently Safari - reject cookies set by MAS, which is in this context a third party. 
The solution is to use the StorageAccess API to determine if this is going to be a problem and, where this is the case, to provide the user with a link to the tool on the partner-tools subdomain. In the first instance this will be added to the Credit Card Calculator tool. 
This work creates a new Dough component that can be re-used across all tools that require it. 
The associated PR is …
=> Third party cookie control

assets/js/components/ThirdPartyCookieAccess.js, lib/dough/version.rb
[TP-12213](https://maps.tpondemand.com/entity/12213-replace-link-on-safari-message-for)
This work essentially replaces a link added in a previous piece of work ([TP-11920](https://maps.tpondemand.com/entity/11920-credit-card-calculator-implement-the-storage)) to provide users of syndicated tools with a means of continuing to use a tool when their browser blocks the use of third party cookies. Originally that referred users to the `partner-tools` sub-domain but that was not always a great experience for the user and not really a correct use of that sub-domain. In this work we are dynamically generating a URL to the tool on the MAS site instead. 
This PR also requires [PR-2329](https://github.com/moneyadviceservice/frontend/pull/2329) on frontend to deploy it to the Credit Card Calculator.
=> 12213 third party cookies update link
